ncf_manager/models/dgii_ws.py
ncf_manager/models/res.py
ncf_manager/static/src/js/marcos.js
ncf_manager/test/__init__.py
ncf_manager/test/test_ncf_manager.py
ncf_manager/views/res_view.xml
requirements.txt

1-Add dgii Webservice trasient class.
2-Extend FieldMany2One widget to query on dgii webservice direct from form and autocomplete general data.
3-Add blank README.md for documentation purpose.
4-add description module from old repo
WARNING: Only work on Many2One partner_id field after accept this PR i'll meke the PR form partner form on text input

Add dgii webservice and autocomple partner from vat idetification

---

.gitignore
ncf_manager/__init__.py
ncf_manager/__manifest__.py
ncf_manager/controllers/__init__.py
ncf_manager/controllers/controllers.py
ncf_manager/models/res.py
ncf_manager/static/src/js/ncf_manager.js
ncf_manager/static/src/lib/bootstrap-typeahead.js
ncf_manager/static/src/xml/ncf_manager.xml
ncf_manager/views/assets_backend.xml
ncf_manager/views/res_view.xml

This PR add autofill partner from DGII with name input on res_partner form

Feature/dgii autocomplete widget issue #20

---

ncf_manager/models/account_invoice.py

Este PR hace un refactor a las validaciones de comprobantes, agrega la funcionalidad con stdnum, y modifica el approach para validar las facturas de proveedores, mejorando la legibilidad del código y removiendo redundancias.

[REF] Change approach for NCF validation on invoices

---

ncf_manager/i18n/es_DO.po

Teaching the new angrybirds how to change i18n on module

Change i18n label from factura to contabilidad

---

ncf_pos/__manifest__.py
ncf_pos/static/src/xml/pos.xml

TG-8 #closed

---

ncf_pos/__manifest__.py
ncf_pos/static/src/js/db.js
ncf_pos/views/templates.xml

En el buscador de cliente del pos ahora se puede buscar por rnc o cedula

Feature/search client by rnc and cedula#6

---

ncf_manager/__manifest__.py
ncf_manager/models/__init__.py
ncf_manager/models/account.py
ncf_manager/models/account_invoice.py
ncf_manager/models/account_move.py
ncf_manager/models/ir_sequence.py
ncf_manager/models/res.py
ncf_manager/views/account_invoice_view.xml
ncf_manager/views/account_view.xml
ncf_manager/views/ir_sequence_view.xml

Este PR incluye el nuevo mecanismo de manejo de secuencias de forma dinámica utilizando el subsequence con date_range del modelo ir.sequence, de esta forma se tiene lo mejor de los dos mundos:
1- Vencimientos por Secuencia
2- Cambio de Secuencia de forma dinámica sin crear más de un ir.sequence
También es el primer PR que iniciará el deprecation de los shops en la localización.

[MERGE] New fiscal sequence mechanism implemented with ir.sequence

---

ncf_manager/data/sequences.xml
ncf_manager/models/account_invoice.py
ncf_manager/models/account_move.py
ncf_manager/views/account_invoice_view.xml

[ADD] Internal invoice number to customer and supplier invoices

---

ncf_manager/models/account_invoice.py

[ADD] Validation to verify the journal is minor and assign it

---

ncf_manager/__manifest__.py
ncf_manager/data/sequences.xml
ncf_manager/models/account_invoice.py
ncf_manager/wizard/__init__.py
ncf_manager/wizard/update_internal_sequence_wizard.py
ncf_manager/wizard/update_sequence_wizard_view.xml

[ADD] Wizard allow an easy way to configure internal sequences

---

ncf_pos/static/src/js/screens.js
ncf_pos/static/src/xml/pos.xml

[Add] Add the credit note button to the payment screen

---

ncf_pos/static/src/css/ncf_pos.css
ncf_pos/static/src/js/chrome.js
ncf_pos/static/src/js/models.js
ncf_pos/static/src/xml/pos.xml
ncf_pos/views/templates.xml

This PR adds the layout to the POS ticket!
TODO: Show the NCF!! Waiting for "Online/Offline NCF solution" approach
This close #61

[Add] Make new ticket layout

---

ncf_pos/static/src/js/screens.js
ncf_pos/static/src/xml/pos.xml

[Add] text input popup to payment screen

---

ncf_pos/static/src/js/models.js
ncf_pos/static/src/js/screens.js
ncf_pos/static/src/xml/pos.xml

Adding vertical scrolling on invoices query screen

---

ncf_pos/models/pos_config.py
ncf_pos/models/pos_order.py
ncf_pos/static/src/js/models.js

[FIX] Reconcile payment on pos order after creation

---

ncf_manager/models/res.py

Fix conditional to validate model to assign company and sale fiscal type

---

ncf_manager/controllers/controllers.py
ncf_manager/models/res.py
ncf_pos/static/src/js/models.js
ncf_pos/static/src/js/screens.js

[IMP] Validations for the customer creation in POS

---

ncf_invoice_template/report/report_invoice.xml
ncf_invoice_template/report/report_templates.xml

[REF] only invoices has dgii template

---

ncf_pos/__manifest__.py
ncf_pos/models/pos_order.py
ncf_pos/security/ir.model.access.csv
ncf_pos/static/src/js/models.js
ncf_pos/static/src/js/screens.js

[FIX] Generation and assignment NCF to the invoice on POS

---

ncf_pos/models/pos_order.py
ncf_pos/static/src/js/models.js
ncf_pos/static/src/js/screens.js
ncf_pos/static/src/xml/ncf_ticket.xml
ncf_pos/views/pos_view.xml

[REF] Change NCF loading on ticket & Credit Note origin assignment

---

ncf_invoice_template/report/report_invoice.xml
ncf_invoice_template/report/report_templates.xml

- [FIX] show Factura Gubernamental when it have to
- [ADD] added company address fields

[11.0][ncf_invoice_template] Fixes

---

ncf_pos/static/src/js/models.js

[FIX] The crossing of orders when printing

---

ncf_pos/static/src/js/screens.js
ncf_pos/static/src/xml/pos.xml

[FIX] Allow editing customer information

---

ncf_manager/models/res.py
ncf_pos/static/src/js/models.js
ncf_pos/static/src/xml/ncf_ticket.xml
ncf_pos/static/src/xml/pos.xml

[FIX] Changing NCF default value when creating a customer

---

ncf_manager/models/account.py
ncf_manager/models/account_invoice.py
ncf_manager/models/res.py
ncf_manager/views/account_invoice_view.xml
ncf_pos/models/pos_order.py
ncf_pos/static/src/js/models.js
ncf_pos/static/src/js/screens.js
ncf_pos/views/pos_view.xml

Closes #209 
Closes #167 (won't fix)

[MERGE] Main changes from 11.0 into 10.0-for stable release

---

ncf_manager/models/res.py

This commit fix wrong country coming up by default when creating new contact.

Countryfix

---

ncf_invoice_template/__init__.py
ncf_invoice_template/models/__init__.py
ncf_invoice_template/models/account_invoice.py
ncf_invoice_template/report/report_invoice.xml

[11.0][ncf_invoice_template] Fixed ITBIS column values computation

---

ncf_invoice_template/report/report_invoice.xml

Mostrar descuento total solo si se ha aplicado algún descuento a alguna línea.
https://github.com/odoo-dominicana/l10n-dominicana/issues/262

[IMP] Mostrar descuento solo si existe

---

ncf_pos/static/src/js/screens.js

[FIX] Avoid the selection of the first company when is searching by name in the DGII WS and the result is only one

---

ncf_manager/wizard/account_invoice_refund.xml

Arreglo de condiciones domain line (48, 55)

Arreglo de condicion domain

---

ncf_manager/models/res_currency.py

[FIX] ncf_manager: make Central Bank rate importer work

---

ncf_purchase/views/res_partner_views.xml

REF change field position

---

ncf_manager/models/account.py
ncf_manager/models/account_invoice.py
ncf_manager/models/ir_sequence.py

**Artículo 7**. Del Comprobante de Compras. Se entenderá comprobante de compras, aquellos comprobantes emitidos por las personas físicas y jurídicas cuando adquieran bienes o servicios de personas no registradas como contribuyentes. La factura sustentada en un comprobante de compras deberá contener el formato indicado en la Norma General núm. 06-2018.
**Párrafo I**. Es obligación del emisor del comprobante fiscal verificar en el portal web dispuesto por la DGII a tales fines, que la persona sobre la cual se emite el comprobante no se encuentre registrada como contribuyente ante la DGII. Cuando la DGII verifique que el comprobante ha sido emitido a personas registradas como contribuyentes, no será admitido para fines de deducción del Impuesto Sobre la Renta (ISR) ni del Impuesto …

[REF] ncf_manager: made purchase order compliant to Norma 05-19

---

ncf_invoice_template/report/report_invoice.xml

This commit adds partners tel and cellphone numbers if exists

Ncf invoice template partners numbers

---

l10n_do_accounting/__manifest__.py
l10n_do_accounting/data/account_fiscal_type_data.xml
l10n_do_accounting/models/account_fiscal_sequence.py
l10n_do_accounting/models/account_invoice.py
l10n_do_accounting/models/account_journal.py
l10n_do_accounting/views/account_fiscal_sequence_views.xml
l10n_do_accounting/views/account_invoice_views.xml
l10n_do_accounting/views/account_journal_views.xml
l10n_do_accounting/views/res_partner_views.xml

primeros pasos de restricciones

12.0 pro guavana

---

l10n_do_accounting/models/account_fiscal_sequence.py

[FIX] error in type of fiscal sequence type

---

ncf_manager/models/res.py

[IMP] ncf_manager: Enable add custom validations on create res.partner method.
- Moved body of create method to validate_on_create to allow override and add custom validations.
- Added validate_vat method to allow override and add custom validations before call validate_rnc_cedula method.
[REF] ncf_manager: Moved duplicate code to new method.
- Moved duplicate code of methods onchange_partner_name and onchange_partner_vat to new method validate_vat_onchange.

[IMP] ncf_manager: Enable add custom validations on create res.partner method.

---

l10n_do_accounting/data/account_fiscal_type_data.xml
l10n_do_accounting/models/account_fiscal_sequence.py
l10n_do_accounting/models/account_invoice.py
l10n_do_accounting/views/account_invoice_views.xml

- [IMP] l10n_do_accounting: added an index to invoice fiscal_type_id fields
- [REF] l10n_do_accounting: use more explicit fiscal type types
- [REF] l10n_do_accounting: do not overwrite NC button

[IMP] l10n_do_accounting: fiscal type types improvements

---

l10n_do_accounting/models/account_fiscal_sequence.py
l10n_do_accounting/views/account_invoice_views.xml

- [IMP] l10n_do_accounting: change invoice fiscal_type_id field domain
- [FIX] l10n_do_accounting: fix warning gap compute

[IMP] l10n_do_accounting: improvements

---

ncf_pos/security/ir.model.access.csv

Soluciona el problema de permisos en el punto de venta

[FIX] add access to pos user

---

dgii_reports/models/account_invoice.py
dgii_reports/models/dgii_report.py

[FIX] dgii_reports: Multiple date miss-conversions & method references

---

ncf_manager/models/res.py

when the vat number isn't registered on the dgii issue fixed

[FIX] ncf_manager: when the vat number isn't registered on the dgii

---

l10n_do_accounting/demo/res_partner_demo.xml
l10n_do_accounting/tests/common.py
l10n_do_accounting/tests/test_account_fiscal_sequence.py
l10n_do_accounting/tests/test_account_invoice.py

- [FIX] l10n_do_accounting: wtf with this expense type?
- [REF] l10n_do_accounting: move environment() function to common file
- [IMP] l10n_do_accounting: added invoice fiscal_sequence_status tests
- [IMP] l10n_do_accounting: added partner sale_fiscal_type tests
- [IMP] l10n_do_accounting: added partner purchase_fiscal_type and expense_type
- [IMP] l10n_do_accounting: added required document UserError test
- [IMP] l10n_do_accounting: added amount total limit when no vat tests
- [REF] l10n_do_accounting: removed TODO note

[ADD] l10n_do_accounting: added fiscal invoice tests

---

dgii_reports/models/dgii_report.py
dgii_reports/models/res_partner.py
requirements.txt

1-**EL PAIS ESTA SALIENDO POR SIGLAS PERO DEBE DE SER EL CODIGO NUMERICO DEL PAIS**.
Ejemplo US = 840
2-**EL TIPO DE SERVICIO ADQUIRIDO ESTA SALIENDO CON EL CODIGO CON UN CERO DELANTE**.
Ejemplo Gastos de Representación = 05,
Pero debe de ser Gastos de Representación = 5
3-**LA PARTE RELACIONADA ESTA SALIENDO VACIO PERO DEBE DE SER 0 O 1**
Si es SI el valor será 1
Si es NO el valor será 0

[IMP] dgii_reports: mejoras, correcciones 609

---

l10n_do_accounting/i18n/es_DO.po

This will translate into Spanish the current English word.

Update Translate to Spanish

---

Dockerfile
cloudbuild.yaml

This should be in Dockerdoo, but we need it ASAP

[FIX] Dockerfile: Add chrome and websocket-client for UI tests

---

l10n_do_account_cancel/i18n/es_DO.po
l10n_do_pos/i18n/es_DO.po

[ADD] l10n_do_account_cancel: Added es_DO translation

---

.gitlab-ci.yml
.gitmodules
cloudbuild.yaml
ncf_manager/__manifest__.py
ncf_manager/models/res.py
oca_dependencies.txt

DGII API has been very unstable, and API Indexa is much more stable, so we're using it instead

[FIX] ncf_manager: Use API Indexa RNC validator

---

ncf_manager/models/account_invoice.py

* [IMP] ncf_manager: Avoid orders with discounts to hang on pos
* [REF] ncf_manager: flake8 fix

[IMP] ncf_manager: Avoid orders with discounts to hang on pos (#586)

---

ncf_manager/models/account_invoice.py

Do not validate eNCF against service as on branch 12

[FIX] ncf_manager: Do not validate eNCF against service as on branch 12

---

l10n_do_accounting/models/account_invoice.py

This fix to validate the final invoice on e-CF and pass the validation of e-cf Credit Note type

[FIX] Validation with e-CF and on Credit Note

---

l10n_do_accounting/views/report_invoice.xml

[FIX] l10n_do_accounting: AttributeError: account.move object has no attribute origin_out

---

ncf_manager/wizard/account_invoice_refund.py

[FIX] ncf_manager: IndexError when creating Refund on 'modify' mode

---

cloudbuild.yaml
l10n_do_accounting/i18n/es_DO.po
l10n_do_accounting/models/account_journal.py
l10n_do_accounting/models/account_move.py
l10n_do_accounting/views/account_move_views.xml
l10n_do_accounting/wizard/account_move_reversal.py
l10n_do_accounting/wizard/account_move_reversal_views.xml
l10n_do_debit_note/__init__.py
l10n_do_debit_note/__manifest__.py
l10n_do_debit_note/i18n/es_DO.po
l10n_do_debit_note/models/__init__.py
l10n_do_debit_note/models/account.py
l10n_do_debit_note/models/account_journal.py
l10n_do_debit_note/models/account_move.py
l10n_do_debit_note/views/account_views.xml
l10n_do_debit_note/wizard/__init__.py
l10n_do_debit_note/wizard/account_debit_note.py
l10n_do_debit_note/wizard/account_debit_note_views.xml

- [REF] l10n_do_accounting: remove all Debit Notes features
- [ADD] added new module l10n_do_debit_note
- [IMP] l10n_do_debit_note: added es_DO translation

[13.0][ADD] added new module l10n_do_debit_note

---

dgii_reports/models/account_invoice.py
dgii_reports/models/dgii_report.py

If the actual rate goes up, this was making the reported amount to be bigger than the actual reality

[FIX] dgii_reports: Consider invoice date not current date
