ncf_pos/i18n/es_DO.po
The text "Tax ID" was changed to "RNC"
=> Changed i18n "ID de impuesto" to "RNC" in module point of sale

ncf_pos/static/src/js/screens.js, ncf_pos/static/src/xml/pos.xml
En este PR se evita que desde la pantalla de listado de clientes se pueda cambiar tipo fiscal y la cedula o RNC.
Se determinó que estos campos deben ser readonly desde la creacion de un contacto en adelante para evitar errores de asignacion de rnc a otras personas o entidades.
=> Turning readonly to vat and fiscal type (Ref: Resolve #66)

ncf_manager/models/account_move.py, ncf_manager/models/ir_sequence.py
El parámetro `sale_fiscal_type` solo debe enviarse a través de la factura si el diario de esa factura tiene el ncf_control activado, de lo contrario se estaría requiriendo que los comprobantes estén configurados cuando no son necesarios.
=> [FIX] Just require NCF configuration for invoices with NCF journals

ncf_invoice_template/report/report_invoice.xml
Al instalar el modulo de stock, si el modulo de ncf_invoice_template se instala primero lanza error, ya que no encuentra el div reference. Este PR arregla dicho error.
=> Fix labels and add div name

ncf_manager/controllers/controllers.py
Este PR agrega la capacidad de CORS a la ruta del webservice de la DGII.  
@gustavovalverde puedes probarlo. Ya funciona nitido fuera del POS. En el POS funciona la busqueda, pero si solo colocas el rnc/cedula y le das a guardar, se guardara el rnc/cedula. No funciona igual que el backend, pero es porque no esta programado asi aun.
@eneldoserrata hay que anotar eso por ahi, por si acaso da de nuevo.
Close #168
=> Allowing CORS on dgii-related route

ncf_manager/models/account_invoice.py
He creado un método que consulta la ocurrencia del número, compañía, cliente, diario y tipo de factura, solo cuando la factura sea tipo 'out_invoice'.
De esta forma, el constraint que ya existe y que aplica para 'in_invoice', siga funcionando igual.
Ver link:
https://github.com/odoo-dominicana/l10n-dominicana/blob/ec56027b323c8184f46d69e61c446290749ebb2f/ncf_manager/models/account_invoice.py#L157
Close #227
=> Método para validar la no duplicidad de NCF en Facturas de clientes

ncf_manager/models/account_invoice.py
Cuando se selecciona Diario de Gastos Menores en Facturas de Proveedor en un ambiente multicompany, se recibe este error porque por cada compañía puede tener su propio diario de gastos menores.
=> [FIX][11.0][ncf_manager] Expected Singletone Error

ncf_manager/views/account_invoice_view.xml
clone #220 
1. sale_fiscal_type readonly in draft if move_name already have assigned sequence
2. shows the sequence assigned in the draft and cancel states
=> [FIX] close #220

ncf_invoice_template/report/report_invoice.xml
Se corrige consumidor final que no mostraba el nombre del cliente y tambien se añade que muestre el nombre del parent si existe en vez del partner.
=> [FIX] Consumidor Final not showing name

ncf_manager/models/account_invoice.py
Considering that partner_id is a table level required field
I call it using this format: vals['partner_id'] and construct
the object at the same time.
Also fixed that check_dgii() method was receiving partner id,
instead of partner vat.
=> [FIX] ncf_manager: InvalidFormat error on create

ncf_invoice_template/report/report_invoice.xml
Added missing code line which evaluate if invoice line is ITBIS exempt.
=> [FIX] ncf_invoice_template: show E when exempt itbis

ncf_manager/models/ir_sequence.py
If an invoice from a date older than the current year was tried to be used, it would commonly fail if there wasn't a date sequence  with the invoice date.
This was caused because the date context was not passed to Odoo's sequence, but just to the NCF sequence.
=> [FIX] ncf_manager: Fix Odoo's sequence with date_range

ncf_manager/models/account_invoice.py, ncf_manager/tests/test_customer_invoice.py
**Artículo 3**. Del Comprobante para Regímenes Especiales. Son aquellos comprobantes utilizados para facturar las transferencias de bienes o prestación de servicios **exentos del ITBIS y/o ISC** a las personas físicas o jurídicas acogidas a regímenes especiales de tributación mediante leyes especiales, contratos o convenios debidamente ratificados por el Congreso Nacional.
=> [ADD] ncf_manager: added method to validate special expempt invoices

ncf_manager/models/account.py, ncf_manager/models/account_invoice.py, ncf_manager/models/ir_sequence.py
**Artículo 9**. Del Comprobante para Pagos al Exterior. Se entenderá como comprobante para pagos al exterior, aquellos emitidos por concepto de pago de rentas gravadas de fuente dominicana a personas físicas o jurídicas no residentes fiscales obligadas a realizar la retención total del Impuesto sobre la Renta, de conformidad a los artículos 297 y 305 del Código Tributario.
=> [ADD] ncf_manager: added new purchase NCF: Pagos al Exterior

ncf_manager/models/account_invoice.py, ncf_purchase/models/account_invoice.py
The wrong method "_onchange_origin" was being replaced from upstream after march 11,
there's a commit removing the behavior that was affecting the localization
https://github.com/odoo/odoo/commit/1be873d40d7aa8b1959e3c5a1ec6a6ead2323b6a, but after
https://github.com/odoo/odoo/commit/a441e89c9fdeed9dfe92da10689c3cc981fead50 we had
the issue once again.
As Odoo is keeping this behavior on purchase_order_change and this can't be inherited
we have to completetely override this function.
This commit completely reverts 3f31b05 made by @yasmanycastillo
=> [FIX] ncf_manager: Do not change invoice reference from the purchase

ncf_manager/views/account_invoice_view.xml
This was allowing Minor and Informal invoices to be changed, which is a wrong behavior with critical consequences.
=>  [FIX] ncf_manager: Do not allow NCF modification on non-fiscal invoices

ncf_pos/models/pos_order.py, ncf_pos/static/src/js/screens.js
Impacted versions
V10, V11, v12
Steps to reproduce
Configurar un numero máximo en el diario de factura. Sobrepasar este numero.
Current behavior
Sobrepasa el número máximo.
Expected behavior
Le ponga un freno al usuario. Talvez tener casilla para override en punto de ventas, para evitar conflictos en facturación.
Video/Screenshot link (optional)
=> Enforce max numbers on ncf_pos

l10n_do_accounting/__manifest__.py, l10n_do_accounting/security/res_groups.xml, l10n_do_accounting/views/account_invoice_views.xml
In order to avoid possible fraud, access to the creation of credit notes was restricted with a user group.
=> [IMP] l10n_do_accounting: restrict credit notes by user group

l10n_do_accounting/demo/account_fiscal_sequence_demo.xml, l10n_do_accounting/models/account_invoice.py, l10n_do_accounting/tests/common.py, l10n_do_accounting/tests/test_account_invoice.py
- [IMP] l10n_do_accounting: added percetage fiscal refund tests
- [REF] l10n_do_accounting: remove unnused package
- [IMP] l10n_do_accounting: added fixed_amount fiscal refund tests
- [FIX] l10n_do_accounting: do not ask for fiscal sequence if puchase a… …
- [IMP] l10n_do_accounting: added fiscal vendor credit notes amount and… …
- [REF] l10n_do_accounting: removed TODO note
- [IMP] l10n_do_accounting: added customer debit notes percentage/fixed… …
- [IMP] l10n_do_accounting: added vendor debit notes percentage/fixed a… …
=> [IMP] l10n_do_accounting: finish fiscal invoice unitests

dgii_reports/controllers/dgii_reports_controllers.py, dgii_reports/static/src/js/widget.js, dgii_reports/views/dgii_report_templates.xml
Con este widget, las url tendran **"dgii_reports/"** delante para evitar colisión con otros módulos de website.
Antes:
- midominio.com/<valor_campo_con_widget_url>
Ahora:
- midominio.com/**dgii_reports/**<valor_campo_con_nuevo_widget_url>
=> [IMP] dgii_reports: Adding a url widget to build a custom url for reports

ncf_pos/models/pos_order.py
Fixes: 
pos_order.py", line 120, in _process_order
order.add_payment(self._payment_fields(payments[2]))
File "/odoo/odoo-server/src/custom/iterativo/l10n-dominicana/ncf_pos/models/pos_order.py", line 325, in add_payment
move_line_ids = out_refund_invoice.move_id.line_ids
File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 947, in _get_
record.ensure_one()
File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4428, in ensure_one
raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.invoice(83648, 82123)
=> better imp avoining singleton error

l10n_do_accounting/models/account_invoice.py, l10n_do_accounting/models/account_journal.py, l10n_do_accounting/views/account_journal_views.xml, l10n_do_accounting/wizard/account_invoice_refund.py
With this we can turn off/on validation of ncf on Purchase Journal if DGII is offline we can turn off, 
But I think later on we should check if stdnum or other server is online/offline and then raise an alert and mark the NCF as **"not validated with DGII"** but create a button of I don't know now to validate is the server is online again. It's just guessing... 
But right now it's alternative.
=> [ADD] Turn off/on DGII validation on Purchase

ncf_manager/models/account_invoice.py
[IMP] ncf_manager: Avoid orders with discounts to hang on pos
[REF] ncf_manager: flake8 fix
[FIX] ncf_manager: singleton error when customer invoice doesn't have sale_fiscal_type or supplier invoice's journal doesn't have purchase_type. Traceback:
`_compute_sequence_almost_depleted
if sequence.number_next_actual >= sequence.warning_ncf:
File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 1003, in __get__
record.ensure_one()
File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4744, in ensure_one
raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: ir.sequence.date_range(65, 68, 139)`
These affects v12 as well
=> 11.0 Fixes the following

ncf_manager/models/account_invoice.py
Al crear una Nota de Crédito, por defecto no tomaba el valor correspondiente para el **Tipo de Costos y Gastos** lo cual podía ser una limitante que bloqueaba al usuario de poder editar una factura en algunos casos como si la factura se creaba y validaba automáticamente al cancelar y conciliar o desde un borrador que el usuario olvidaba seleccionar el Tipo de Costos y Gastos correspondiente.
Por defecto a nivel contable el Tipo de Costos y Gastos correcto es el de la factura original.
=> [FIX] ncf_manager: adding expense_type value for Credit Note

ncf_invoice_template/report/report_invoice.xml
Removed "on x amount" label from the invoice tax summary to avoid confusion when dealing with multiple tax groups. 
**------------- VS -------------**
**Applies only to V12.0**
=> [IMP] ncf_invoice_template: tax sum readability

ncf_manager/__manifest__.py, ncf_manager/models/account_invoice.py
Tal como acordamos en Instagram.  Realice las pruebas y con tan solo remover el módulo l10n_do_rnc_validation del __manifest__.py funciona todo normalmente.  Puedo buscar RNC tanto por el número como por el nombre.   
Instalar el modulo l10n_do_rnc_validation sería opcional para mejorar la disponibilidad de la consulta de los RNC cuando el DGII realice cambios o no este disponible.
=> [FIX] ncf_manager: removing the optional external dependency

ncf_manager/models/account_invoice.py
When you set a customer on a customer invoice, the sale fiscal type should be set automatically getting the value from customer sale fiscal type.
=> Removing Sale Fiscal Type check onchanging partner
